apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: argocd
  labels:
    app: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
      tier: backend
  template:
    metadata:
      labels:
        app: redis-server
        tier: backend
    spec: # Pod spec
      containers:
      - name: redis
        image: redislabs/redismod:latest
        command: ["redis-server"]
        args: ["--loadmodule", "/usr/lib/redis/modules/redisjson.so"]
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-lb
  namespace: argocd
  labels:
    app: redis-server
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: redis-lb
  selector:
    app: redis-server
    tier: backend
  type: LoadBalancer
---
